KMOD=	trivial-6d4c9cf5e022a07ea8013a4b07a30a88270c65dfd5223ccc3964d9a7b4525008
SRCS=	trivial.c hide_kernelmodule.c escalate.c hook_mkdir.c hook_getentries.c hook_read.c hook_open.c hook_rename.c

.include <bsd.kmod.mk>
